java:
    8home:  /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
spinfer:
    home:   /Users/anilkoyuncu/projects/fixminer/spinfer/spinfer.native
coccinelle:
    home:   /Users/anilkoyuncu/projects/fixminer/spinfer/statics

dataset:
#    home:   /Users/anilkoyuncu/projects/fixminer/fixminer-core/python/data/gumInputLinux
    inputPath : /Users/anil.koyuncu/projects/release/fixminer-data/patches
    repo:   /Users/anil.koyuncu/projects/release/fixminer-data/datasets

fixminer:
    projectType : java
    datapath: /Users/anil.koyuncu/projects/release/fixminer-data/


    pjName : patches
    portDumps : 6399
    numOfWorkers : 14
    hostname : localhost
    hunkLimit : 2
    patchSize : 50

    projectList : fuse
    inputPath : /Users/anil.koyuncu/projects/release/fixminer-data/patches
    redisPath : /Users/anil.koyuncu/projects/release/fixminer_source/python/data/redis
    srcMLPath :  /usr/local/bin/srcml
